include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/app_localizations*"

  errors:
    invalid_annotation_target: ignore
