name: movie
description: "Movie App Using TMDB API"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 3rd party - Localization
  intl: any
  flutter_localizations:
    sdk: flutter

  # 3rd party - UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  infinite_carousel: ^1.1.1
  cached_network_image: ^3.3.1

  # 3rd party - Resources Manager
  flutter_gen: ^5.5.0+1

  # 3rd party - Environment Manager
  envied: ^0.5.4+1

  # 3rd party - State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # 3rd party - Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # 3rd party - Local Storage
  flutter_secure_storage: ^9.0.0

  # 3rd party - Networking
  dio: ^5.4.0

  # 3rd party - Serialization
  equatable: ^2.0.5
  collection: ^1.18.0
  connectivity_plus: ^6.0.1
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  # 3rd party - Routing
  go_router: ^14.1.4

  # 3rd party - Grouping
  dartz: ^0.10.1
  logger: ^2.3.0
  nested: ^1.0.0

dependency_overrides:
  json_annotation: ">=4.9.0"
  json_serializable: ">=6.8.0"

dev_dependencies:
  # 3rd party
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.3.2
  injectable_generator: ^2.4.1
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/app/res/
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: AppAssets

  colors:
    enabled: true
    outputs:
      class_name: AppColor
    inputs:
      - assets/colors/colors.xml

  fonts:
    enabled: true
    outputs:
      class_name: FontsFamily

flutter:
  uses-material-design: true

  assets:
    - assets/icons/badge/
    - assets/icons/common/
    - assets/images/logo/

  fonts:
    - family: NetflixSans
      fonts:
        - asset: assets/fonts/NetflixSans-Regular.otf
          weight: 400
        - asset: assets/fonts/NetflixSans-Medium.otf
          weight: 500
        - asset: assets/fonts/NetflixSans-Light.otf
          weight: 300
        - asset: assets/fonts/NetflixSans-Bold.otf
          weight: 700
